const sites = [
  "https://stackexchange.com",
  "https://stackoverflow.com",
  "https://superuser.com",
  "https://askubuntu.com",
  "https://serverfault.com",
  "https://dev.to",
  "https://freecodecamp.org",
  "https://hackernoon.com",
  "https://devdocs.io",
  "https://medium.com",
  "https://css-tricks.com",
  "https://cssreference.io",
  "https://digitalocean.com",
  "https://docker.com",
  "https://git-scm.com",
  "https://github.com",
  "https://github.io",
  "https://godoc.org",
  "https://learnxinyminutes.com",
  "https://lobste.rs",
  "https://logrocket.com",
  "https://npmjs.com",
  "https://ohshitgit.com",
  "https://pypi.org",
  "https://readthedocs.org",
  "https://realpython.com",
  "https://shellscript.sh",
  "https://w3schools.com",
  "https://ycombinator.com",
  "https://yourbasic.org",
];

export default sites;
